### ISSUE TITLE
Awesome Example, any chance on updating to vue 3?

### ISSUE THREAD

**Issue by funkel1989** [shawnwildermuth/VueInCore#1]
Just looking for your opinions in doing something like this with Vue 3. With easier support on SSR rendered pages in vue 3 without nuxt now I'm not sure how viable a solution like this would be with Vue 3, IMO.

**Comment by shawnwildermuth** [comment]
Yeah, not a fan of SSR, I'm moving more towards this as my solution:

http://wildermuth.com/2021/02/15/I-Was-Wrong---Hosting-SPAs-in-ASP-NET-Core
