### ISSUE TITLE
how to include prod vue scripts with hashes in razor page

### ISSUE THREAD

**Issue by smadep** [shawnwildermuth/VueInCore#2]
Hi!

Couldn't leave comment/question with article anymore, so I'm asking here .....

How do I include proper vue scripts (npm build)
```
<script src=/js/chunk-vendors.6ef87ee7.js></script>
<script src=/js/index.9d28a0e2.js></script>
```

in the razor page

```
@page
@model IndexModel
@{
  ViewData["Title"] = "Home page";
}
@section Scripts {
  <script src="~/app/js/chunk-vendors.js"></script>
  <script src="~/app/js/index.js"></script>
}
<div id="app"></div>
```
My main purpose to use your approach would be to be independent of basepath during vue build,
use app.UsePathBase("/optionalpath") and inject it as global js variable...

Thanks and Best Regards,
Stefan

**Comment by shawnwildermuth** [comment]
I usually turn off hashes in the vue.config.js file so I don't have to do that. Otherwise, it's hard to get new hashes on every call. (Since I'm using ASP.NET Core, I use asp-use-versioning instead of Vue hashes).

https://cli.vuejs.org/config/#filenamehashing
