### ISSUE TITLE
Could this approach be used with Vite as well?

### ISSUE THREAD

**Issue by jonathancounihanneem** [shawnwildermuth/VueInCore#3]
Hi @shawnwildermuth thanks for this blog post, really like the approach and it is very helpful.

Do you know if this is possible with Vite? From what I can see you must have an index.html file as well as main.js for each page that you want to create a separate bundle/page section for. Looking at the rollup options for Vite: https://vitejs.dev/config/build-options.html#build-rollupoptions, it does not seem this is possible in the same way as the Pages variable as used for vue.config.ts?

I am looking for a way to use the razor cshtml files as the launching point for each page and then a "mini-spa" on each main razor page (so I can use ASP.NET antiforgery token for example, and any other razor goodies...)

Do you have any advice on how to do that?

Thanks.

**Comment by SQLSourcerer** [comment]
@jonathancounihanneem does this help? https://stackoverflow.com/questions/70522494/multiple-entry-points-in-vite

**Comment by jonathancounihanneem** [comment]
Thanks @SQLSourcerer I forgot I asked this question actually! :) 
I have managed to get this working using another of Shaun's blog posts : https://wildermuth.com/2023/01/18/vite-in-asp-net-core-projects/

**Comment by shawnwildermuth** [comment]
In case you missed it, I have a Coding Shorts video of it as well:

https://www.youtube.com/watch?v=NG3KAng2mAI&ab_channel=ShawnWildermuth
